spring.application.name=venue-service

server.port=8083


# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/venuedb
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
